In [1]:
import timeit
import numpy as np
from time import time

In [2]:
from numba import cuda
import numba as nb
import math

In [3]:
def init_kernel_bias(num_inp_channels, kernel_size, num_kernels,mean=0,std=0.01):
    shape = [num_inp_channels, kernel_size, kernel_size, num_kernels]
    weights = std*np.random.randn(*shape) + mean
    # weights/=np.sqrt(num_inp_channels)
    bias = std*np.random.randn(1,num_kernels) + mean
    return weights, bias

In [4]:
w0,b0=init_kernel_bias(num_inp_channels=32,kernel_size=3,num_kernels=128)

In [5]:
inp=np.random.randn(128,64,64,32)

In [6]:
#inp[batches,row,col,d],w0(d,ksz,ksz,num_ker),b0[1,num_ker],stride[row,col]
padding=0
stride=[1,1]
ipp=inp.transpose(0,3,1,2)  #ipp[batches,d,row,col]
output=[]
ksz=w0.shape[1]
num_ker=w0.shape[3]
if not padding: #take care of padding in backprop too
    padding=(ksz-1)//2  #currently don't give 'even' ksz
out_row,out_col=((ipp.shape[2]-ksz+2*padding)//stride[0]+1),((ipp.shape[3]-ksz+2*padding)//stride[1]+1)
batches,d,row,col=ipp.shape
row+=2*padding
col+=2*padding
padded=np.zeros((batches,d,row,col))
padded[:,:,padding:-padding,padding:-padding]=ipp

In [7]:
img=padded[0]

In [8]:
# %%timeit
window=(np.arange(ksz)[:,None]*row+np.arange(ksz)).ravel()+np.arange(d)[:,None]*row*col
slider=(np.arange(out_row*stride[0])[:,None]*row+np.arange(out_col*stride[1]))
ind = window.ravel()+slider[::stride[0],::stride[1]].ravel()[:,None]
# bind= np.arange(batches)[:,None]*d*row*col+ind.ravel()
kern = w0.reshape(-1,num_ker)
# output=(np.dot(np.take(padded, bind).reshape(-1,d*ksz*ksz), kern)).reshape(batches,out_row,out_col,num_ker)

In [3]:
print(cuda.gpus)

<Managed Device 0>


In [4]:
cuda.select_device(0)

<weakproxy at 0x7f2b8f8b4b88 to Device at 0x7f2b8f8a50f0>

In [5]:
# %%time
# Initialize the data arrays
A = np.random.randn(32*2, 32*3)
B = np.random.randn(3*32, 32)

In [6]:
%%time
# Copy the arrays to the device
A_global_mem = cuda.to_device(A)
B_global_mem = cuda.to_device(B)

# Allocate memory on the device for the result
C_global_mem = cuda.device_array((32*2, 32))

CPU times: user 2.79 ms, sys: 307 µs, total: 3.1 ms
Wall time: 2.17 ms


In [7]:
%%time
# Configure the blocks
threadsperblock = (16,16)
blockspergrid_x = int(math.ceil(A.shape[0] / threadsperblock[0]))
blockspergrid_y = int(math.ceil(B.shape[1] / threadsperblock[1]))
blockspergrid = (blockspergrid_x, blockspergrid_y)

CPU times: user 10 µs, sys: 1 µs, total: 11 µs
Wall time: 13.4 µs


In [8]:
blockspergrid

(4, 2)

In [9]:
(A.nbytes+B.nbytes+np.dot(A,B).nbytes)/1024/1024

0.0859375

In [44]:
# CUDA kernel
@cuda.jit
def matmul(A, B, C):
    """Perform matrix multiplication of C = A * B
    """
    row, col = cuda.grid(2)
    if row < C.shape[0] and col < C.shape[1]:
        tmp = 0.
        for k in range(A.shape[1]):
            tmp += A[row, k] * B[k, col]
        C[row, col] = tmp

In [45]:
%%time
matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)

CPU times: user 189 ms, sys: 272 µs, total: 190 ms
Wall time: 188 ms


In [46]:
%%time
C = C_global_mem.copy_to_host()
print(C.shape)

(64, 32)
CPU times: user 710 µs, sys: 66 µs, total: 776 µs
Wall time: 607 µs


In [47]:
%%time
np.allclose(C,np.dot(A,B))

CPU times: user 1.3 ms, sys: 120 µs, total: 1.42 ms
Wall time: 948 µs


True

In [48]:
np.dot(A,B)

array([[ -0.21309449,   2.89234672,  28.20324537, ..., -14.19437499,
          3.97631953, -19.85510025],
       [  7.79791636,   8.69099402, -19.05600696, ...,   5.10313222,
         23.15987213, -14.31547735],
       [ -5.62363989, -11.57985623,  -0.81119961, ...,   6.15165425,
          6.46526696, -15.27875407],
       ...,
       [-15.96582059,  -1.89555769,   4.86732631, ...,  17.79446482,
          4.05454805,  20.05742225],
       [  6.26804982,  15.04490977,   0.58337399, ...,  -8.24276073,
        -22.72991009, -23.79241361],
       [  5.1795037 ,  -9.69664089,  -9.41470239, ...,   3.58212059,
          0.82304345,   5.880077  ]])

In [49]:
C

array([[ -0.21309449,   2.89234672,  28.20324537, ..., -14.19437499,
          3.97631953, -19.85510025],
       [  7.79791636,   8.69099402, -19.05600696, ...,   5.10313222,
         23.15987213, -14.31547735],
       [ -5.62363989, -11.57985623,  -0.81119961, ...,   6.15165425,
          6.46526696, -15.27875407],
       ...,
       [-15.96582059,  -1.89555769,   4.86732631, ...,  17.79446482,
          4.05454805,  20.05742225],
       [  6.26804982,  15.04490977,   0.58337399, ...,  -8.24276073,
        -22.72991009, -23.79241361],
       [  5.1795037 ,  -9.69664089,  -9.41470239, ...,   3.58212059,
          0.82304345,   5.880077  ]])

In [16]:
import ctypes

In [17]:
cudlib=ctypes.CDLL('libcuda.so')

In [18]:
cudlib.cuInit(0)

0

In [101]:
%time
@cuda.jit
def my_kernel_2D(io_array):
    x, y = cuda.grid(2)
    if x<io_array.shape[0] and y<io_array.shape[1]:
        io_array[x,y]*=8

data = np.ones((16, 16))
data_glob=cuda.to_device(data)
threadsperblock = (32, 32)
blockspergrid_x = math.ceil(data.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(data.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)
my_kernel_2D[blockspergrid, threadsperblock](data_glob)
print(data_glob.copy_to_host())

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs
[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [102]:
%%time
output=np.empty((batches,out_row*out_col,num_ker))
for i,img in enumerate(padded):      #img[d,row,col]
    # windows(out_row*out_col, ksz*ksz*d) . kernels(d*ksz*ksz,num_ker)
    output[i]=np.dot(img.take(ind), kern)
output+=b0
ans2=output.reshape(batches,out_row,out_col,num_ker)

CPU times: user 4.79 s, sys: 163 ms, total: 4.96 s
Wall time: 1.33 s


In [19]:
A.shape,B.shape

((64, 96), (96, 32))

In [38]:
TPB=16
@cuda.jit
def fast_matmul(A,B,C):
    sA=cuda.shared.array(shape=(TPB,TPB),dtype=nb.float32)
    sB=cuda.shared.array(shape=(TPB,TPB),dtype=nb.float32)
    x,y=cuda.grid(2)
    tx=cuda.threadIdx.x
    ty=cuda.threadIdx.y
    if x>=C.shape[0] and y>=C.shape[1]:
        return
    tmp=0
    for i in range(A.shape[1]//TPB):  # for number of blocks
        sA[tx,ty]=A[x,ty+i*TPB]       # preLoad data into shared memory
        sB[tx,ty]=B[tx+i*TPB,y]
        
        cuda.syncthreads()            # wait for loading
        for j in range(TPB):
            tmp+=sA[tx,j]*sB[j,ty]
        cuda.syncthreads()            # wait for computation
    C[x,y]=tmp

In [39]:
%%time
fast_matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)

CPU times: user 255 ms, sys: 6.84 ms, total: 261 ms
Wall time: 260 ms


In [40]:
%%time
C = C_global_mem.copy_to_host()
print(C.shape)

(64, 32)
CPU times: user 1.67 ms, sys: 157 µs, total: 1.82 ms
Wall time: 3.45 ms
